$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json
name: insurance-endpoint
auth_mode: key
description: Managed online endpoint for insurance binary classification model
tags:
  model: insurance-lgbm
  framework: lightgbm

